version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: nft
      MYSQL_USER: root
      MYSQL_PASSWORD: root12345
      MYSQL_ROOT_PASSWORD: root12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
